env:
  - LIBATOMIC_VERSION=7.2alpha4 LIBUNWIND_VERSION=1.0.1
before_install: 
  - sudo add-apt-repository -y ppa:ubuntu-cloud-archive/icehouse-staging
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcre3-dev 
  - sudo apt-get install -y libunwind8-dev
  
install: cmake -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-g -O3 -U_FORTIFY_SOURCE" . && sudo make install
script: igprof -o ls.gz -mp ls && igprof-analyse -r MEM_TOTAL ls.gz
